CREATE TABLE [dbo].[CatalogHistory] (
    [ItemID]         UNIQUEIDENTIFIER NOT NULL,
    [Path]           NVARCHAR (425)   NOT NULL,
    [Name]           NVARCHAR (425)   NOT NULL,
    [ParentID]       UNIQUEIDENTIFIER NULL,
    [Type]           INT              NOT NULL,
    [Content]        VARBINARY (MAX)  NULL,
    [Intermediate]   UNIQUEIDENTIFIER NULL,
    [SnapshotDataID] UNIQUEIDENTIFIER NULL,
    [LinkSourceID]   UNIQUEIDENTIFIER NULL,
    [Property]       NTEXT            NULL,
    [Description]    NVARCHAR (512)   NULL,
    [Hidden]         BIT              NULL,
    [CreatedByID]    UNIQUEIDENTIFIER NOT NULL,
    [CreationDate]   DATETIME         NOT NULL,
    [ModifiedByID]   UNIQUEIDENTIFIER NOT NULL,
    [ModifiedDate]   DATETIME         NOT NULL,
    [MimeType]       NVARCHAR (260)   NULL,
    [SnapshotLimit]  INT              NULL,
    [Parameter]      NTEXT            NULL,
    [PolicyID]       UNIQUEIDENTIFIER NOT NULL,
    [PolicyRoot]     BIT              NOT NULL,
    [ExecutionFlag]  INT              NOT NULL,
    [ExecutionTime]  DATETIME         NULL,
    [SubType]        NVARCHAR (128)   NULL,
    [ComponentID]    UNIQUEIDENTIFIER NULL,
    [ContentSize]    BIGINT           NULL,
    [IsDeleted]      BIT              NOT NULL,
    [DeletionDate]   DATETIME         NULL,
    CONSTRAINT [PK_CatalogHistory] PRIMARY KEY NONCLUSTERED ([ItemID] ASC)
);

